Mission7/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission7.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;

        public CartSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }

        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Mission7/Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission7.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["categoryType"];
            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Mission7/Views/Shared/BookSummary.cshtml
@{
}
@model Book

@*Here I used bootstrap to make the heading of the card have a dark background and white text.*@
<div class="card text-white bg-dark" style="margin:10px;">
    <div class="card-header">
        <div class="row">
            <div class="col">
                <h2>@Model.Title by: @Model.Author</h2>
            </div>
            <div class="col-3">
                <h2 class="text-sm-right">@Model.Price.ToString("c")</h2>
                
            </div>
            <div class="col-1">
                <form method="post" asp-page="/Purchase">
                    <input type="hidden" asp-for="@Model.BookId" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

                    <span class="card-text float-end">
                        @*Here I used bootstrap to make the button have a light color.*@
                        <button type="submit" class="btn btn-light btn-lg">Purchase</button>
                    </span>
                </form>
            </div>
        </div>
        
        
    </div>

    @*Here I used bootstrap to make the body of the card have a light background and black text*@

    <div class="card-body bg-light text-black">
        @*Here I used bootstrap to make a list group to display information on each book*@
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Publisher: @Model.Publisher</li>
            <li class="list-group-item">Classification: @Model.Classification</li>
            <li class="list-group-item">Category: @Model.Category</li>
            <li class="list-group-item">Page Count: @Model.PageCount</li>
            <li class="list-group-item">ISBN: @Model.Isbn</li>
        </ul>
        

    </div>
</div>

Mission7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    

</head>
<body>
    <div class="row bg-dark text-white p-2">
        <div class="col">
            <span class="navbar-brand m-lg-2">Bookstore</span>
        </div>
        <div class="col-6 text-end">
            <vc:cart-summary></vc:cart-summary>
        </div>

    </div>

    <div class="row m-1 p-1">


        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>

        <div id="types" class="col" style="margin-left: 5px;">
            <h2 style="margin-bottom: 3rem;">Sort by category:</h2>
            <vc:types></vc:types>
        </div>

    </div>


</body>
</html>